### ISSUE TITLE
Expected empty line between multiple components

### ISSUE THREAD

**Issue by geniusgordon** [styled-components/stylelint-processor-styled-components#9]
I'm getting a **rule-non-nested-empty-line-before** error when I have multiple components in one file

I've got a file like this

```js
import styled from 'styled-component';

const TextA = styled.span`
  color: blue;
`

const TextB = styled.span`
  color: red;
`
```

and got this error
```
7:1  ✖  Expected empty line before non-nested rule   rule-non-nested-empty-line-before
```

I've console.log the extractedCSS and it looks like this
```css
.selector {
  color: blue;
}  /* <----- missing a newline here */
.selector {
  color: red;
}
```

I'm using:
* stylelint-config-standard@15.0.0
* stylelint-processor-styled-components@0.0.4
* stylelint@7.6.0
